# Задание 1.1

In [10]:
import numpy as np

A = np.array(([i%2 for i in range(8)] + [int(not(i%2)) for i in range(8)])*4)
A1 = A.copy()
B = A.reshape(8,8)
print(B)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Задание 1.2

In [30]:
import numpy as np

A = [np.arange(0, 5) for i in range(5)]

print(*A)

[0 1 2 3 4] [0 1 2 3 4] [0 1 2 3 4] [0 1 2 3 4] [0 1 2 3 4]


# Задание 1.3

In [4]:
import numpy as np

np.random.random((3, 3, 3))

array([[[0.49966482, 0.2120158 , 0.08335144],
        [0.14678721, 0.82495954, 0.03596571],
        [0.93866051, 0.23131354, 0.40142235]],

       [[0.02039443, 0.0700486 , 0.12564137],
        [0.68310224, 0.27116384, 0.5827085 ],
        [0.15255123, 0.31143984, 0.98494406]],

       [[0.31391329, 0.64128702, 0.2633962 ],
        [0.98568642, 0.90445335, 0.45542113],
        [0.30983315, 0.83994693, 0.67820125]]])

# Задание 1.4

In [6]:
import numpy as np
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# Задание 1.5

In [15]:
import numpy as np
x = np.random.rand(10)
sorted(x, reverse= True)

[0.8480926752148621,
 0.7186071061136396,
 0.6967531561566668,
 0.5533572570378288,
 0.3436328797651499,
 0.3229758193328549,
 0.31511254915179865,
 0.2607933181401163,
 0.12011584670871256,
 0.0187366271682905]

# Задание 1.6

In [22]:
import numpy as np
a = [[1,2], [3,4]]
x = np.matrix(a)
print(np.shape(x))

(2, 2)


# Задание 2.1

In [27]:
import pandas as pd
c = {'x':4, 'y':8}
d = {'x':16, 'y':-2}
a = pd.Series(data=c, index=['x', 'y'])
b = pd.Series(data=d, index=['x', 'y'])
evkl = ((max(a['x'], b['x'])- min(a['x'], b['x']))**2 + (max(a['y'], b['y'])- min(a['y'], b['y']))**2)**0.5
evkl

15.620499351813308

# Задание 2.2

In [30]:
import pandas as pd
import numpy as np

df = pd.read_csv('australian.csv')
df.head()

A1   A2   A3  A4  A5  A6  A7  A8  A9  A10  A11  A12  A13  A14  A15_class
0   1   65  168   2   4   4  39   0   0    1    1    2   32  161          0
1   0   72  123   2   8   4   5   0   0    1    0    2   53    1          0
2   0  142   52   1   4   4  31   0   0    1    1    2   98    1          0
3   0   60  169   1   5   3   1   1   1   12    1    2    1    1          1
4   1   44  134   2   6   4  46   1   1   15    0    2   18   68          1

# Задание 2.3

In [32]:
import pandas as pd
import numpy as np

df = pd.read_csv('australian.csv')
df.head(2)

A1  A2   A3  A4  A5  A6  A7  A8  A9  A10  A11  A12  A13  A14  A15_class
0   1  65  168   2   4   4  39   0   0    1    1    2   32  161          0
1   0  72  123   2   8   4   5   0   0    1    0    2   53    1          0

In [33]:
df.tail(3)

A1   A2   A3  A4  A5  A6  A7  A8  A9  A10  A11  A12  A13  A14  A15_class
687   0   32  145   2   6   4   3   1   0    1    0    2   32    1          1
688   0  122  193   2  14   8  67   1   1    2    0    2   38   12          1
689   1  245    2   2  10   4   2   0   1    2    0    1  159    1          1

In [34]:
df.shape

(690, 15)

In [35]:
df.describe()

A1          A2          A3          A4          A5          A6  \
count  690.000000  690.000000  690.000000  690.000000  690.000000  690.000000   
mean     0.678261  148.686957   82.682609    1.766667    7.372464    4.692754   
std      0.467482   92.932052   58.792636    0.430063    3.683265    1.992316   
min      0.000000    1.000000    1.000000    1.000000    1.000000    1.000000   
25%      0.000000   72.000000   33.000000    2.000000    4.000000    4.000000   
50%      1.000000  134.500000   70.000000    2.000000    8.000000    4.000000   
75%      1.000000  219.750000  125.750000    2.000000   10.000000    5.000000   
max      1.000000  350.000000  215.000000    3.000000   14.000000    9.000000   

               A7          A8          A9         A10         A11         A12  \
count  690.000000  690.000000  690.000000  690.000000  690.000000  690.000000   
mean    37.147826    0.523188    0.427536    3.298551    0.457971    1.928986   
std     36.328826    0.499824    0.495080    4.034413    0.498592    0.298813   
min      1.000000    0.000000    0.000000    1.000000    0.000000    1.000000   
25%      5.000000    0.000000    0.000000    1.000000    0.000000    2.000000   
50%     26.000000    1.000000    0.000000    1.000000    0.000000    2.000000   
75%     61.000000    1.000000    1.000000    4.000000    1.000000    2.000000   
max    132.000000    1.000000    1.000000   23.000000    1.000000    3.000000   

              A13         A14   A15_class  
count  690.000000  690.000000  690.000000  
mean    58.797101   55.143478    0.444928  
std     46.150187   72.695049    0.497318  
min      1.000000    1.000000    0.000000  
25%     24.000000    1.000000    0.000000  
50%     53.000000    6.000000    0.000000  
75%     95.000000  107.750000    1.000000  
max    171.000000  240.000000    1.000000

In [37]:
df.iloc[1:4]

A1   A2   A3  A4  A5  A6  A7  A8  A9  A10  A11  A12  A13  A14  A15_class
1   0   72  123   2   8   4   5   0   0    1    0    2   53    1          0
2   0  142   52   1   4   4  31   0   0    1    1    2   98    1          0
3   0   60  169   1   5   3   1   1   1   12    1    2    1    1          1

In [38]:
df[df['A4'] == 1].head()

A1   A2   A3  A4  A5  A6  A7  A8  A9  A10  A11  A12  A13  A14  A15_class
2    0  142   52   1   4   4  31   0   0    1    1    2   98    1          0
3    0   60  169   1   5   3   1   1   1   12    1    2    1    1          1
8    1  126   33   1   2   8  65   0   0    1    0    2   61  117          0
12   1   49   40   1   8   8  34   1   1    4    1    2   45   79          0
18   1   42   40   1   4   4   4   0   0    1    0    2   45    5          0

# Задание 3.1

In [24]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
import scipy.stats as stats

df = pd.read_csv('https://raw.githubusercontent.com/akmand/datasets/master/iris.csv')
df.head()

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             3.6              1.4             0.2  setosa

In [25]:
feature1 = [[x] for x in df.sepal_length_cm]
feature1 = np.array(feature1)
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0,1))
scaled_feature1 = minmax_scale.fit_transform(feature1)
df1 = df
df1.sepal_length_cm = scaled_feature1
df1.head()

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222             3.5              1.4             0.2  setosa
1         0.166667             3.0              1.4             0.2  setosa
2         0.111111             3.2              1.3             0.2  setosa
3         0.083333             3.1              1.5             0.2  setosa
4         0.194444             3.6              1.4             0.2  setosa

In [27]:
feature2 = [[x] for x in df.sepal_width_cm]
feature2 = np.array(feature2)
scaled_feature2 = stats.zscore(feature2)
df2 = df1
df2.sepal_width_cm = scaled_feature2
df2.head()

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222        1.032057              1.4             0.2  setosa
1         0.166667       -0.124958              1.4             0.2  setosa
2         0.111111        0.337848              1.3             0.2  setosa
3         0.083333        0.106445              1.5             0.2  setosa
4         0.194444        1.263460              1.4             0.2  setosa